### ISSUE TITLE
Update bundle options

### ISSUE THREAD

**Issue by vpassapera** [vpassapera/TdnForgeBundle#35]
Update the bundle to support the following type of configuration:

```yml
tdn_forge:
    writer:
        standard: ~ #Default is symfony2
    generators:
        auto: ~ #Default: false, if enabled, a resource watcher will be kicked off in the back-ground (it can be tailed using tail -f <log_dir>/generators.log)
                # that will auto-generate code as you change your entities for each of the generators that are enabled
        exclude_entities: ~ #Exclude from all generators
        skeleton_overrides: ~ #Skeleton override directory, auto-detects generator overrides.

        controller: ~
            auto: ~ #Default: false, if enabled, a resource watcher will be enabled for this particular generator. (it can be tailed using tail -f <log_dir>/generators.log)
            enabled: ~
            exclude_entities: ~ #Exclude from controller generator
        form: ~
            auto: ~ #Default: false, if enabled, a resource watcher will be enabled for this particular generator. (it can be tailed using tail -f <log_dir>/generators.log)
            enabled: ~
            exclude_entities: ~ #Exclude from form generator
        handler: ~
            auto: ~ #Default: false, if enabled, a resource watcher will be enabled for this particular generator. (it can be tailed using tail -f <log_dir>/generators.log)
            enabled: ~
            exclude_entities: ~ #Exclude from handler generator
        manager: ~
            auto: ~ #Default: false, if enabled, a resource watcher will be enabled for this particular generator. (it can be tailed using tail -f <log_dir>/generators.log)
            enabled: ~
            exclude_entities: ~ #Exclude from manager generator
        routing: ~
            auto: ~ #Default: false, if enabled, a resource watcher will be enabled for this particular generator. (it can be tailed using tail -f <log_dir>/generators.log)
            enabled: ~
            exclude_entities: ~ #Exclude from routing generator
        sonata: ~
            auto: ~ #Default: false, if enabled, a resource watcher will be enabled for this particular generator. (it can be tailed using tail -f <log_dir>/generators.log)
            enabled: ~
            exclude_entities: ~ #Exclude from sonata generator
```
Use https://lurker.readthedocs.org/en/latest/ to watch for file changes.

- [ ] Add watch command
- [ ] Create event listener for generators
- [ ] Create event listener for writter
- [ ] Move all generator factory/setup code out of commands and into listener.
- [ ] Move all writer code out of command and into listener.
- [ ] Update bundle configuration
